# Generated by Django 3.0 on 2020-07-20 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('hire_date', models.DateField()),
                ('birthday_date', models.DateField()),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=20)),
                ('sales_volume', models.FloatField()),
                ('agent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='sales.Agents')),
            ],
        ),
    ]
